Initial project setup + Docker setup
Applifting/link-shortener pull request #1
Opened 2020-04-06 18:56 UTC by vojta-janousek

- A basic setup for connecting Sanic to MySQL
- An API to test the connection working + test mysql.connector package

- Environment variables will be hidden in the future
- Database and a table within it will be initialized on starting the server in the future
- Operations will be handled directly as opposed to via requests

2020-04-07 09:37 UTC, radektheloner commented
Could you please replace the `requirements.txt` file with a `pyproject.toml` file and use `poetry install` rather than `pip install` since [Poetry](https://python-poetry.org/) is the tool we use in other projects?

2020-04-07 09:38 UTC, radekholy24 requested changes
- [x] Could you please replace the `requirements.txt` file with a `pyproject.toml` and `poetry.lock` files and use `poetry install` rather than `pip install` since [Poetry](https://python-poetry.org/) is the tool we use in other projects?

2020-04-07 09:40 UTC, radekholy24 requested changes
- [x] What is the purpose of `requirements - not working.txt`, please?

2020-04-07 09:55 UTC, radekholy24 reviewed
Just a recommendation for you:
In Red Hat, our lawyers recommended us to put a little comment at the beginning of each open-souced file like this:
```python
# Copyright (C) 2020 Link Shortener Authors
# Licensed under the MIT (Expat) License. See the LICENSE file found in the
# top-level directory of this distribution.
```
while also adding an `AUTHORS` file that contains names of all the contributors (copyright owners). Just to be safe in case someone just copies only one file to their own project.

2020-04-07 10:27 UTC, radekholy24 requested changes
Other than that looks good to me. I didn't review the endpoints since I believe all of them are going to be removed later anyway. So, please resolve the comments above and I'll take another look then.

2020-04-07 10:27 UTC, radektheloner commented on src/server.py
> +        mycursor.execute('SHOW DATABASES')
Can you please use [aiomysql](https://github.com/aio-libs/aiomysql) instead of the `mysql-connector` since this is the tool we use in other projects?

2020-04-07 10:27 UTC, radektheloner commented on src/server.py
> +        mycursor.execute('SHOW DATABASES')
Also, can you please use an SQL query builder (like [pypika](https://pypika.readthedocs.io/en/latest/) nebo [SQLAlchemy Core](https://docs.sqlalchemy.org/en/14/core/tutorial.html)) or is this something you plan to do later?

2020-04-07 13:17 UTC, vojta-janousek commented
Done:
- Authors header
- Poetry integration
- DB Initialisation + population on project container start
- Simple link redirection API

To be done:
- Replace mysql.connector with aiomysql
- Use an SQL builder to form queries

2020-04-07 18:56 UTC, radekholy24 reviewed
Just a recommendation:
In the Listeners section, there is an example of using listeners to set the database up before the server starts and to store a connection in the request context:
https://sanic.readthedocs.io/en/latest/sanic/middleware.html#listeners
I think you may find it useful.

Also, storing a connection pool instead of a connection would be even nicer.

2020-04-07 19:15 UTC, radekholy24 reviewed
Fine, looks good to me.

There are some leftovers, e.g. some commented lines, outdated readme, `requirements.txt`, but meh...

Regarding the SQL query builders, there is a quite good example in the aiomysql documentation, I'd say...
https://aiomysql.readthedocs.io/en/latest/sa.html

So, if you add that, I think I can merge it then.

2020-04-09 13:38 UTC, vojta-janousek commented
To do for current pull request:

- 

To do before production:

- Hide environment variables

2020-04-10 17:18 UTC, radekholy24 requested changes
Just one last recommendation. Instead of using the global variables, you can store the engine in the `app` object like this:
```python
@app.listener('before_server_start')
async def setup_db(app, loop):
    app.db = await create_engine(
        ...
    )
```

and then use it like this:
```python
@app.route('/<link_endpoint>')
async def redirect_link(request, link_endpoint):
    async with request.app.db.acquire() as conn:
        ...
```

Please let me know, if you want to do this. Otherwise, since I don't see any major issues, I'll merge it.

2020-04-12 21:11 UTC, radekholy24 approved these changes
Fine with me. Thank you!

2020-04-12 21:12 UTC, merged