Prometheus
Applifting/link-shortener pull request #11
Opened 2020-06-10 14:08 UTC by vojta-janousek

2020-06-10 14:22 UTC, radekholy24 requested changes

2020-06-10 14:22 UTC, radekholy24 commented on link_shortener/view_routes.py
> +                redirect_counter.inc()
Can you please add the [labels](https://github.com/prometheus/client_python#labels)? We need a `link_id` label that contains the ID of the link that is counted so that users can watch the stats per link.

Also a [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) label ~and the IP address of the user~ might be interesting but consider them optional.

2020-06-10 15:27 UTC, vojta-janousek commented on link_shortener/view_routes.py
> +                redirect_counter.inc()
Labels added. My browser does not send referer header, but it returned "None" and no errors.

2020-06-11 14:53 UTC, radekholy24 approved these changes
Cool, looks good to me. Can you please rebase it on current `applifting/master`? I will merge it then.

2020-06-14 15:16 UTC, vojta-janousek commented
Conflict resolved, branch is ready to be merged now. Thank you!

2020-06-14 15:27 UTC, merged